---
- hosts: localhost
  become: yes
  tasks:
    - name: Install PHP 7 Packages
      become: true
      yum:
        name: "{{ yum_php_packages }}"
        enablerepo: ius
      when: yum_php_packages is defined
      notify: restart php7-fpm on centos

    - name: Start php7-fpm on centos
      become: true
      service:
        name: php-fpm
        state: started
        enabled: yes

